.\" vim: ts=8 sw=8 noet cc=80

.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.\" Portable package manager made in POSIX shell script
.\" Copyright (C) 2023 astral
.\" 
.\" This file is part of ppmpss.
.\" 
.\" ppmpss is free software: you can redistribute it and/or modify it under the
.\" terms of the GNU General Public License as published by the Free Software
.\" Foundation, either version 3 of the License, or (at your option) any later
.\" version.
.\" 
.\" ppmpss is distributed in the hope that it will be useful, but WITHOUT ANY
.\" WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
.\" FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
.\" details.
.\" 
.\" You should have received a copy of the GNU General Public License along
.\" with ppmpss. If not, see <https://www.gnu.org/licenses/>.

.TH PPMPSS-EM 1
.SH NAME
ppmpss-em \- emerge a package into the system
.SH SYNOPSIS
.B ppmpss em
[\fIOPTIONS\fR] [\fIPKG\fR]...
.SH DESCRIPTION
Emerge the specified \fIPKG\fR into the system.
.SH OPTIONS
.TP
.B \-s
Synch the local ppmpss repo with the remote one.
.TP
.B \-u [\fIPKG\fR]...
Update the specified \fIPKG\fR. If no \fIPKG\fR is specified, update every
emerged package.
.TP
.B \-R <\fIREPO\fR>
Emerge a package from the specified \fIREPO\fR.
